// Generated by IcedCoffeeScript 108.0.11
(function() {
  app.controller('RootCtrl', [
    '$scope', '$http', function($scope, $http) {
      $scope.settings = settings;
      $scope.nav = function(menu, parents) {
        var item, _i, _len, _results;
        $scope.currentMenus = [];
        _results = [];
        for (_i = 0, _len = arguments.length; _i < _len; _i++) {
          item = arguments[_i];
          _results.push($scope.currentMenus.push(item));
        }
        return _results;
      };
      return $scope.nav($scope.settings.menus[0]);
    }
  ]);

}).call(this);
