// Generated by IcedCoffeeScript 108.0.11
(function() {
  app.directive('formInput', [
    function() {
      return {
        template: "<div class=\"form-group form-group-sm\">\n    <label ng-bind=\"ngLabel?ngLabel:label\"></label>\n    <sup ng-if=\"isRequired\">*</sup>\n    <span class=\"pull-right\" ng-bind=\"ngDes?ngDes:des\"></span>\n    <input name=\"{{ngName?ngName:name}}\" type=\"text\" class=\"form-control\"/>\n</div>",
        replace: true,
        transclude: true,
        restrict: 'E',
        scope: {
          label: '@',
          name: '@',
          required: '@',
          pattern: '@',
          des: '@',
          ngLabel: '=',
          ngName: '=',
          ngRequired: '=',
          ngPattern: '=',
          ngDes: '='
        },
        link: function(scope, ele, attrs) {
          var input, regPattern;
          scope.isRequired = scope.ngRequired || scope.required;
          if (scope.isRequired) {
            ele.attr('data-required', true);
          }
          if (scope.ngPattern || scope.pattern) {
            regPattern = scope.ngPattern ? scope.ngPattern : scope.pattern;
            ele.attr('data-pattern', regPattern);
          }
          input = ele.find('input');
          if (attrs.placeholder) {
            return input.attr('placeholder', attrs.placeholder);
          }
        }
      };
    }
  ]);

}).call(this);
