// Generated by IcedCoffeeScript 108.0.11
(function() {
  this.settings = {
    appName: 'Bndy CMS',
    appShortName: 'CMS',
    appVersion: '1.0.0',
    appUrl: 'http://www.bndy.net',
    enableSidebar: true,
    menus: [
      {
        icon: 'fa fa-home fa-fw',
        text: 'Home',
        description: 'Control Panel',
        url: '/home'
      }, {
        text: 'Multilevel',
        children: [
          {
            text: 'Level One 1'
          }, {
            text: 'Level One 2'
          }, {
            text: 'Level One 3'
          }
        ]
      }, {
        text: 'LABELS',
        isHeader: true
      }, {
        text: 'Primary'
      }, {
        text: 'Warning'
      }, {
        text: 'Default'
      }
    ]
  };

}).call(this);
